### ISSUE TITLE
SilentDragon MediaPack

### ISSUE THREAD

**Issue by UrgeyBergy** [MyHush/MediaPack#2]
[HUSH SilentDragon.pdf](https://github.com/MyHush/MediaPack/files/3321993/HUSH.SilentDragon.pdf)
[HUSH SilentDragon symbol only.pdf](https://github.com/MyHush/MediaPack/files/3321994/HUSH.SilentDragon.symbol.only.pdf)
![HUSH SilentDragon white background](https://user-images.githubusercontent.com/37842843/60040644-763d7000-9687-11e9-9d06-04819f27fe0d.png)
![HUSH SilentDragon type only white background](https://user-images.githubusercontent.com/37842843/60040645-763d7000-9687-11e9-95b8-ca2df2457b55.png)
![HUSH SilentDragon type only transparent background](https://user-images.githubusercontent.com/37842843/60040647-763d7000-9687-11e9-8854-f6e9bca222a2.png)
![HUSH SilentDragon transparent background](https://user-images.githubusercontent.com/37842843/60040650-76d60680-9687-11e9-86e1-889287fc6382.png)
![HUSH SilentDragon symbol only white background](https://user-images.githubusercontent.com/37842843/60040651-76d60680-9687-11e9-8d01-3adfc1368759.png)
![HUSH SilentDragon symbol only transparent background](https://user-images.githubusercontent.com/37842843/60040652-776e9d00-9687-11e9-923b-c4b51a2d6bd9.png)

**Comment by gilardh** [comment]
Include in https://github.com/MyHush/MediaPack/pull/3

**Comment by gilardh** [comment]
@leto We can close this issue now.
